version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: responsive-library-server
    container_name: responsive-library-node-server
    command: npm run start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - responsive-library-network
  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - responsive-library-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: responsive-library-client
    container_name: responsive-library-react-client
    command: npm run start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - responsive-library-network

networks:
    responsive-library-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local