name: Node.js CI

on:
  push:
    branches: [ PUM03-021 ]
  pull_request:
    branches: [ PUM03-021 ]

jobs:
  build:
    runs-on: ubuntu-latest # change this later to docker containers

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
        with: 
          ref: 'PUM03-021' 
          
      - name: Start containers 
        run: docker-compose -f "docker-compose.yml" up -d --build
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: ls
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
